INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('19130535', 'Ivan', 'Herrera', 'Garcia', 22, 'Helicopero');



INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('19130527', 'Fatima', 'Goretti', 'Yescas', 30, 'Woman');
