INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('19130535', 'Ivan', 'Herrera', 'Garcia', 22, 'Helicopero');




INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('1', '1', '1', '1', 1, '1');

INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('2', '2', '2', '2', 0, '2');

INSERT dbo.INFORMACION(NUM_CONTROL, APE_P, APE_M, NOMBRE, EDAD, GENERO) VALUES ('17130071', 'Torres', 'Vega', 'Victor Manuel', 22, 'Hombre');
