CREATE TABLE [dbo].[BITACORA] (
  [ID_BITACORA] [int] IDENTITY,
  [EVENTO] [varchar](10) NOT NULL,
  [FECHA] [date] NOT NULL,
  [USUARIO] [varchar](50) NOT NULL,
  [TABLA_AFECTADA] [varchar](50) NOT NULL,
  CONSTRAINT [PK_BITACORA_CODIGO] PRIMARY KEY CLUSTERED ([ID_BITACORA])
)
ON [PRIMARY]
GO